name: GH Deploy

on:
 push:
  branches:
   - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Install racket and deps
      run: |
        sudo apt install racket
        raco pkg install --checksum fb0eeab2171251368d51d41c7298ae7d96735530 --deps search-auto pollen
        raco pkg install --checksum 1d01c9ee274f66de4f193c73ff391ed6be553448 --deps search-auto megaparsack
    - name: Pollen publish
      run: |
        raco pollen render
        raco pollen publish
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v4 # or specific "vX.X.X" version tag for this action
      with:
        path: /home/runner/publish

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
